#!/bin/bash

# Dual-Purpose AI Chatbot Platform Setup Script
# Generated on: 2024-12-19T10:30:00Z
# Generated by syed

set -e

echo "🚀 Setting up Dual-Purpose AI Chatbot Platform..."

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "📝 Creating .env file from template..."
    cp env.example .env
    echo "⚠️  Please edit .env file with your configuration:"
    echo "   - Set your OpenAI API key"
    echo "   - Update database passwords if needed"
    echo "   - Configure other settings as required"
    echo ""
    echo "🔑 You can get an OpenAI API key from: https://platform.openai.com/api-keys"
    echo ""
    read -p "Press Enter after you've configured the .env file..."
else
    echo "✅ .env file already exists"
fi

# Create uploads directory
echo "📁 Creating uploads directory..."
mkdir -p backend/uploads

# Build and start the services
echo "🔨 Building and starting services..."
docker-compose up -d --build

# Wait for services to be ready
echo "⏳ Waiting for services to be ready..."
sleep 30

# Check if services are running
echo "🔍 Checking service status..."
docker-compose ps

echo ""
echo "✅ Setup complete!"
echo ""
echo "🌐 Access the application:"
echo "   - Frontend: http://localhost:3000"
echo "   - Backend API: http://localhost:8000"
echo "   - API Documentation: http://localhost:8000/docs"
echo ""
echo "📚 Next steps:"
echo "   1. Register a new user account"
echo "   2. Create an admin user (you may need to manually set role in database)"
echo "   3. Upload documents to the knowledge base"
echo "   4. Start chatting!"
echo ""
echo "🛠️  Useful commands:"
echo "   - View logs: docker-compose logs -f"
echo "   - Stop services: docker-compose down"
echo "   - Restart services: docker-compose restart"
echo "   - Rebuild: docker-compose up -d --build"
echo ""
echo "📖 For more information, see the README.md file" 