/**
 * Customer Chat component with simplified interface for customer support
 * 
 * Generated on: 2024-12-19T10:30:00Z
 * Generated by syed
 */

import React, { useState, useEffect, useRef } from 'react';
import {
  Box,
  Paper,
  TextField,
  Button,
  Typography,
  Avatar,
  List,
  ListItem,
  ListItemText,
  ListItemAvatar,
  Chip,
  Divider,
  CircularProgress,
  Alert,
  IconButton,
  Tooltip,
} from '@mui/material';
import {
  Send as SendIcon,
  Refresh as RefreshIcon,
  Chat as ChatIcon,
  Person as PersonIcon,
  SmartToy as BotIcon,
} from '@mui/icons-material';
import { useQuery, useMutation, useQueryClient } from 'react-query';
import { chatApi, ChatMessage, ChatResponse, Conversation, Message } from '../../services/api.ts';
import toast from 'react-hot-toast';

const CustomerChat: React.FC = () => {
  const [message, setMessage] = useState('');
  const [currentConversationId, setCurrentConversationId] = useState<number | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const queryClient = useQueryClient();

  // Get conversations
  const { data: conversations, isLoading: conversationsLoading } = useQuery(
    'conversations',
    () => chatApi.getConversations(),
    {
      refetchOnWindowFocus: false,
    }
  );

  // Get messages for current conversation
  const { data: conversationMessages, isLoading: messagesLoading } = useQuery(
    ['messages', currentConversationId],
    () => chatApi.getConversationMessages(currentConversationId!),
    {
      enabled: !!currentConversationId,
      refetchOnWindowFocus: false,
    }
  );

  // Send message mutation
  const sendMessageMutation = useMutation(
    (messageData: ChatMessage) => chatApi.sendMessage(messageData),
    {
      onSuccess: (response) => {
        const newMessage: Message = {
          id: response.data.message_id,
          content: response.data.content,
          role: response.data.role,
          conversation_id: response.data.conversation_id,
          sources: response.data.sources,
          confidence_score: response.data.confidence_score,
          model_used: response.data.model_used,
          created_at: response.data.timestamp,
        };

        setMessages(prev => [...prev, newMessage]);
        setCurrentConversationId(response.data.conversation_id);
        setMessage('');
        
        // Refetch conversations to update the list
        queryClient.invalidateQueries('conversations');
        
        toast.success('Message sent successfully!');
      },
      onError: (error: any) => {
        toast.error(error.response?.data?.detail || 'Failed to send message');
      },
    }
  );

  // Update messages when conversation messages change
  useEffect(() => {
    if (conversationMessages?.data) {
      setMessages(conversationMessages.data);
    }
  }, [conversationMessages]);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const handleSendMessage = () => {
    if (!message.trim()) return;

    const messageData: ChatMessage = {
      content: message.trim(),
      conversation_id: currentConversationId || undefined,
      conversation_type: 'customer_support',
    };

    sendMessageMutation.mutate(messageData);
  };

  const handleKeyPress = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      handleSendMessage();
    }
  };

  const handleNewConversation = () => {
    setCurrentConversationId(null);
    setMessages([]);
  };

  const handleSelectConversation = (conversation: Conversation) => {
    setCurrentConversationId(conversation.id);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString();
  };

  const getConfidenceColor = (score: number) => {
    if (score >= 80) return 'success';
    if (score >= 60) return 'warning';
    return 'error';
  };

  return (
    <Box sx={{ display: 'flex', height: 'calc(100vh - 120px)', gap: 2 }}>
      {/* Conversations Sidebar */}
      <Paper sx={{ width: 300, p: 2, display: 'flex', flexDirection: 'column' }}>
        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
          <ChatIcon sx={{ mr: 1 }} />
          <Typography variant="h6">Conversations</Typography>
        </Box>
        
        <Button
          variant="contained"
          fullWidth
          onClick={handleNewConversation}
          sx={{ mb: 2 }}
        >
          New Conversation
        </Button>

        {conversationsLoading ? (
          <CircularProgress />
        ) : (
          <List sx={{ flexGrow: 1, overflow: 'auto' }}>
            {conversations?.data?.map((conversation) => (
              <ListItem
                key={conversation.id}
                button
                selected={currentConversationId === conversation.id}
                onClick={() => handleSelectConversation(conversation)}
              >
                <ListItemText
                  primary={conversation.title || 'New conversation'}
                  secondary={`${conversation.message_count} messages`}
                />
              </ListItem>
            ))}
          </List>
        )}
      </Paper>

      {/* Chat Area */}
      <Paper sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
        {/* Chat Header */}
        <Box sx={{ p: 2, borderBottom: 1, borderColor: 'divider' }}>
          <Typography variant="h6">
            Customer Support Chat
            {currentConversationId && (
              <Chip
                label="Active"
                color="success"
                size="small"
                sx={{ ml: 2 }}
              />
            )}
          </Typography>
        </Box>

        {/* Messages Area */}
        <Box sx={{ flexGrow: 1, overflow: 'auto', p: 2 }}>
          {messagesLoading ? (
            <Box sx={{ display: 'flex', justifyContent: 'center', p: 2 }}>
              <CircularProgress />
            </Box>
          ) : messages.length === 0 ? (
            <Box sx={{ textAlign: 'center', p: 4 }}>
              <ChatIcon sx={{ fontSize: 64, color: 'text.secondary', mb: 2 }} />
              <Typography variant="h6" color="text.secondary" gutterBottom>
                Welcome to Customer Support
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Start a conversation by typing a message below.
              </Typography>
            </Box>
          ) : (
            <List>
              {messages.map((msg, index) => (
                <React.Fragment key={msg.id}>
                  <ListItem
                    sx={{
                      flexDirection: 'column',
                      alignItems: msg.role === 'user' ? 'flex-end' : 'flex-start',
                    }}
                  >
                    <Box
                      sx={{
                        display: 'flex',
                        alignItems: 'flex-start',
                        maxWidth: '70%',
                        flexDirection: msg.role === 'user' ? 'row-reverse' : 'row',
                      }}
                    >
                      <Avatar
                        sx={{
                          bgcolor: msg.role === 'user' ? 'primary.main' : 'secondary.main',
                          mr: msg.role === 'user' ? 0 : 1,
                          ml: msg.role === 'user' ? 1 : 0,
                        }}
                      >
                        {msg.role === 'user' ? <PersonIcon /> : <BotIcon />}
                      </Avatar>
                      <Paper
                        sx={{
                          p: 2,
                          bgcolor: msg.role === 'user' ? 'primary.light' : 'grey.100',
                          color: msg.role === 'user' ? 'white' : 'text.primary',
                        }}
                      >
                        <Typography variant="body1" sx={{ whiteSpace: 'pre-wrap' }}>
                          {msg.content}
                        </Typography>
                        
                        {/* Sources */}
                        {msg.sources && msg.sources.length > 0 && (
                          <Box sx={{ mt: 1 }}>
                            <Typography variant="caption" color="text.secondary">
                              Sources:
                            </Typography>
                            {msg.sources.map((source: any, idx: number) => (
                              <Chip
                                key={idx}
                                label={source.title}
                                size="small"
                                sx={{ mr: 0.5, mt: 0.5 }}
                              />
                            ))}
                          </Box>
                        )}
                        
                        {/* Confidence Score */}
                        {msg.confidence_score && (
                          <Box sx={{ mt: 1 }}>
                            <Chip
                              label={`Confidence: ${msg.confidence_score}%`}
                              color={getConfidenceColor(msg.confidence_score) as any}
                              size="small"
                            />
                          </Box>
                        )}
                        
                        <Typography variant="caption" sx={{ display: 'block', mt: 1 }}>
                          {formatDate(msg.created_at)}
                        </Typography>
                      </Paper>
                    </Box>
                  </ListItem>
                  {index < messages.length - 1 && <Divider />}
                </React.Fragment>
              ))}
              <div ref={messagesEndRef} />
            </List>
          )}
        </Box>

        {/* Message Input */}
        <Box sx={{ p: 2, borderTop: 1, borderColor: 'divider' }}>
          <Box sx={{ display: 'flex', gap: 1 }}>
            <TextField
              fullWidth
              multiline
              maxRows={4}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onKeyPress={handleKeyPress}
              placeholder="Type your message..."
              disabled={sendMessageMutation.isLoading}
            />
            <Button
              variant="contained"
              onClick={handleSendMessage}
              disabled={!message.trim() || sendMessageMutation.isLoading}
              sx={{ minWidth: 56 }}
            >
              {sendMessageMutation.isLoading ? (
                <CircularProgress size={20} />
              ) : (
                <SendIcon />
              )}
            </Button>
          </Box>
        </Box>
      </Paper>
    </Box>
  );
};

export default CustomerChat; 