"""
Main API router for v1 endpoints.

Generated on: 2024-12-19T10:30:00Z
Generated by syed
"""

from fastapi import APIRouter

from app.api.v1.endpoints import auth, chat, documents, users, admin

api_router = APIRouter()

# Include all endpoint routers
api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(chat.router, prefix="/chat", tags=["chat"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"]) 